name: auto assign

on:
  pull_request:
    types: [opened, unassigned]

jobs:
  assign:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ !(github.actor == 'dependabot[bot]' || github.actor == 'github-actions[bot]' || github.actor == 'renovate[bot]') }}
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: gh pr edit $NUMBER --add-assignee $ASSIGNEE
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          ASSIGNEE: ${{ github.event.pull_request.user.login }}
  post-assign:
    needs: assign
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: echo "assignee added"
      - run: cat $GITHUB_EVENT_PATH
      - run: echo ${{ github.event.pull_request.assignees }}
      - run: cat ${{ github.event_path }} | jq '.pull_request.assignees'
      - run: echo ${{ toJSON(github.event.pull_request.assignees)}}
